await Delay(2000);
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
ClickByTag("button");
